[tools]
bun = "1.3.10"
go = "1.25.4"
pnpm = "10.30.3"

[settings]
experimental = true

[env]
TURSO_DATABASE_URL="libsql://rc-west-main-church-of-christ-lousando.aws-us-west-2.turso.io"
TURSO_AUTH_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MG5ENFN5dGloYWhwOWJLY08zc2VibHVSOWNOajRraWVhc1ZLYTl3Qng0CnI4SG0wZ2F4SjdrbnZRdlh0UFU3NHlWamZoUHM2SUdJWlQ5R3g5dEFEZ1UKLT4gJHhMe3t4YEEtZ3JlYXNlIDA9PWAgU2Z5Y1Ugc3gmJWEKNWRZSE02Ui9Cc1ZoZklnQUJHTS9RVjlldlp6aUNDUEY2UWJjenBzR1l4WjBqWEZTM0pMOXZoRlh4SWZ2WWJ2MQp1dHAwb1pLeHVTSEtUS09JSUlOQUFiU0ZrVTRMbStwTElrRnJYUWdtUm1vTm9PQStXOVR0OUZUeWFnCi0tLSBsa2wreGVhQlo5d0FKbnA5VFBpdU1zQUFUc2ZuTUw1MVZQYWRKSlRUdWdRCoGqAJgntaNsd4iiXXuBZ/yEc54sYCZr8K+4B2H9mxgv2fk+67vrQekl07fO5TCGlLvHN7X3dmN05jD4ccVX6d2FFEnC1XcMoqSsH/7/s+ap6G/vnsm4vUNHtf3AyiWcBYu6fXeVWf9Q01mSzIPgOIXVOkEtpcxbOsJdX6WnHcPR8eKu/6WJBQKiStdwbczpO5sbt8ecx6zixxXAQMNrY+jw2SguqEHTMpM/oNqijLvpWUTf2GnuwInDSzcj5D0/eh7AdNQQ1B8y0zSONt45Sl36sFxd1FCYVW+x2xSPYi/iLkbrmjEdWKi9qnHseHP1F6DxoSbXldEqpPhZqUFxDmChqCVilE5m15xo5m+Sbg1jAR6bBUmV/Tma9GIUZStJRoTwHY73t0YMuvZWm0Z5Y9k+3XbZvkHO" }
